site_name: yeyeah的记事本
site_url: http://note.yeyeah.life
repo_url: https://github.com/henry-y/notebook
repo_name: notebook
theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  font:
    code: JetBrains Mono

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  - css/fonts.css
  - css/extra.css
  - css/inst.css
plugins:
  - search:
      lang: zh 
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime